name 'chef_task_3'
maintainer 'Alex Dzyubenko'
maintainer_email 'zzzdzuba@gmail.com'
license 'all_rights'
description 'Installs/Configures chef_task_3'
long_description 'Installs/Configures chef_task_3'
version '0.1.0'
issues_url 'https://github.com/DZUBA/chef_test_3'
source_url 'https://github.com/DZUBA/chef_test_3'

depends 'yum', '~> 4.1.0'
depends 'mysql', '~> 6.0'
depends 'apache2', '~> 3.2.2'
depends 'database', '~> 6.1.1'
ruby depends 'mysql2_chef_gem', '~> 1.0'
depends 'simple_iptables', '~> 0.7.5'
